services:
  app:
    container_name: fss
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Exponer el puerto de Flask
    volumes:
      - ./python:/app  # Montar el código de la aplicación dentro del contenedor
      - ./data:/appdata  # Persistencia de datos de MongoDB
      - ./init.sh:/usr/local/bin/init.sh
    environment:
      - PYTHONUNBUFFERED=1  # Evita problemas de buffering en logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]