services:
  app:
    container_name: fss
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3247:3247"  # Exponer el puerto de Flask
    volumes:
      - ./data:/appdata  # Persistencia de datos de MongoDB + faiss
    environment:
      - PYTHONUNBUFFERED=1
      - ADMIN_PASS=snlrdev2025